### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by LiamBindle** [LiamBindle/MQTT-C#6]
- [x] More testing - *?*
- [x] Documentation of testing - *~1.5 hours*
- [x] Examples - *~1 hour*
- [x] Finish README - *~30 min*
- [x] Finish documentation/editting of documentation - *~1 hour*

Class submission specific (we can use a lot of the documentation for these):
- [x] Design document for project submission. - *~30 min*
- [x] Report mesaurements/simulation results (we could talk about our testing). - *~30 min*
- [x] Evaluate success of the project. - *~30 min*
